insert into user(id, name, hobby, age) values (101, 'adm', 'cycling', 35)
insert into user(id, name, hobby, age) values (102, 'adm', 'swimming', 36)
insert into user(id, name, hobby, age) values (103, 'cdm', 'cycling', 35)
insert into user(id, name, hobby, age) values (104, 'ddm', 'swimming', 37)
insert into user(id, name, hobby, age) values (105, 'edm', 'running', 39)
insert into user(id, name, hobby, age) values (106, 'fdm', 'swimming', 42)
insert into user(id, name, hobby, age) values (107, 'gdm', 'cycling', 20)
insert into user(id, name, hobby, age) values (108, 'hdm', 'running', 15)